name: Sean McMahon
favicon: null
layout_spectrum: 0.06002199975773692
typography_spectrum: 0.6859456712845713
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#180f10'
    - '#4a4542'
    - '#e3dad3'
    - '#b6a59e'
  brandStrength: 0.264192670583725
  lightness: 0.7474489849992096
  saturation: 0.9812614487018436
  rhythmicContrast: 0.5338772567920387
purpose: []
